USE `essentialmode`;

ALTER TABLE `characters` 
ADD COLUMN `lastdigits` VARCHAR(255) NULL DEFAULT NULL;

ALTER TABLE `users`
ADD COLUMN `lastdigits` VARCHAR(255) NULL DEFAULT NULL;

ALTER TABLE `users`
ADD COLUMN `phone` VARCHAR(255) NULL DEFAULT NULL;

ALTER TABLE `users`
ADD COLUMN `email` VARCHAR(255) NULL DEFAULT NULL;

ALTER TABLE `characters`
ADD COLUMN `phone` VARCHAR(255) NULL DEFAULT NULL;

ALTER TABLE `characters`
ADD COLUMN `email` VARCHAR(255) NULL DEFAULT NULL;
